import type {
  ReportCategory,
  ReportCategoryId,
  ReportColumn,
  ReportDefinition,
  FilterKind,
} from "./report.types";

const money: ReportColumn["type"] = "money";
const num: ReportColumn["type"] = "number";
const date: ReportColumn["type"] = "date";
const str: ReportColumn["type"] = "string";

const RANGE: FilterKind[] = ["fromDate", "toDate"];

function def(d: Partial<ReportDefinition> & { id: string; number: string; name: string; category: ReportCategoryId; description: string; columns: ReportColumn[] }): ReportDefinition {
  return {
    filters: [],
    audience: "ALL",
    source: d.id,
    ...d,
  } as ReportDefinition;
}

export const REVENUE_REPORTS: ReportDefinition[] = [
  def({
    id: "deposit-collections",
    number: "2.3",
    name: "DEPOSIT COLLECTIONS",
    category: "REVENUE",
    description: "Deposits received against admissions, procedures and general deposit accounts.",
    filters: [...RANGE, "branch", "paymentMode", "userId", "search"],
    audience: "FINANCE",
    columns: [
      { key: "receivedAt", label: "Date", type: date },
      { key: "depositNumber", label: "Receipt Number", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "department", label: "Department", type: str },
      { key: "amount", label: "Amount", type: money, align: "right", total: true },
      { key: "method", label: "Payment Mode", type: str },
      { key: "receivedBy", label: "User/Cashier", type: str },
      { key: "depositType", label: "Deposit Type", type: str },
      { key: "status", label: "Status", type: str },
    ],
  }),

  def({
    id: "credit-sales",
    number: "2.4",
    name: "CREDIT SALES REPORT",
    category: "REVENUE",
    description: "Credit/outstanding invoices with gross, discount, net, paid and outstanding amounts.",
    filters: [...RANGE, "department", "doctor", "branch", "patient", "status", "search"],
    audience: "FINANCE",
    columns: [
      { key: "issuedDate", label: "Date", type: date },
      { key: "invoiceNumber", label: "Invoice", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "department", label: "Department", type: str },
      { key: "service", label: "Service", type: str },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "net", label: "Net", type: money, align: "right", total: true },
      { key: "paid", label: "Paid", type: money, align: "right", total: true },
      { key: "credit", label: "Credit", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "free-and-concession",
    number: "2.5",
    name: "FREE AND CONS. REPORTS",
    category: "REVENUE",
    description: "Invoices carrying concessions, free services and discounts.",
    filters: [...RANGE, "department", "doctor", "branch", "patient", "search"],
    audience: "FINANCE",
    columns: [
      { key: "issuedDate", label: "Date", type: date },
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "department", label: "Department", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "service", label: "Service", type: str },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "concession", label: "Concession", type: money, align: "right", total: true },
      { key: "free", label: "Free Amount", type: money, align: "right", total: true },
      { key: "net", label: "Net", type: money, align: "right", total: true },
      { key: "reason", label: "Reason", type: str },
    ],
  }),

  def({
    id: "test-price-list",
    number: "2.7",
    name: "TEST PRICE LIST",
    category: "REVENUE",
    description: "Laboratory test catalogue with prices, categories and status.",
    filters: ["search", "test", "status"],
    columns: [
      { key: "name", label: "Test", type: str },
      { key: "category", label: "Test Category", type: str },
      { key: "discipline", label: "Department", type: str },
      { key: "price", label: "Price", type: money, align: "right", total: true },
      { key: "updatedAt", label: "Effective Date", type: date },
      { key: "status", label: "Status", type: str },
    ],
  }),

  def({
    id: "bill-print",
    number: "2.8",
    name: "BILL PRINT",
    category: "REVENUE",
    description: "Search and print/reprint patient bills by bill number, UHID or date.",
    filters: [...RANGE, "patient", "search", "status"],
    audience: "FINANCE",
    columns: [
      { key: "issuedDate", label: "Date", type: date },
      { key: "invoiceNumber", label: "Bill Number", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "totalAmount", label: "Total", type: money, align: "right", total: true },
      { key: "paidAmount", label: "Paid", type: money, align: "right", total: true },
      { key: "dueAmount", label: "Due", type: money, align: "right", total: true },
      { key: "status", label: "Status", type: str },
      { key: "printCount", label: "Prints", type: num, align: "right" },
    ],
  }),

  def({
    id: "day-wise-collection",
    number: "2.9",
    name: "DAY WISE COLLECTION REPORT",
    category: "REVENUE",
    description: "Daily collections split by OPD, IPD, laboratory, radiology, pharmacy and other services.",
    filters: [...RANGE, "branch", "paymentMode", "userId"],
    audience: "FINANCE",
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "opd", label: "OPD", type: money, align: "right", total: true },
      { key: "ipd", label: "IPD", type: money, align: "right", total: true },
      { key: "lab", label: "Laboratory", type: money, align: "right", total: true },
      { key: "radiology", label: "Radiology", type: money, align: "right", total: true },
      { key: "pharmacy", label: "Pharmacy", type: money, align: "right", total: true },
      { key: "other", label: "Other", type: money, align: "right", total: true },
      { key: "total", label: "Total", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "department-wise-revenue",
    number: "2.10",
    name: "DEPARTMENT WISE REVENUE",
    category: "REVENUE",
    description: "Revenue by department with gross, discount, concession, refund, net, paid and outstanding.",
    filters: [...RANGE, "department", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "concession", label: "Concession", type: money, align: "right", total: true },
      { key: "refund", label: "Refund", type: money, align: "right", total: true },
      { key: "net", label: "Net", type: money, align: "right", total: true },
      { key: "paid", label: "Paid", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "discount-outstanding",
    number: "2.11",
    name: "DIS. AND OUTSTANDING REVENUE REPORT",
    category: "REVENUE",
    description: "Invoices with discounts or outstanding balances.",
    filters: [...RANGE, "department", "branch", "patient", "search"],
    audience: "FINANCE",
    columns: [
      { key: "patient", label: "Patient", type: str },
      { key: "invoiceNumber", label: "Bill", type: str },
      { key: "department", label: "Department", type: str },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "concession", label: "Concession", type: money, align: "right", total: true },
      { key: "paid", label: "Paid", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "doctor-wise-income",
    number: "2.12",
    name: "DOCTOR WISE INCOME",
    category: "REVENUE",
    description: "Income generated per doctor from billed services.",
    filters: [...RANGE, "department", "doctor", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "doctor", label: "Doctor", type: str },
      { key: "department", label: "Department", type: str },
      { key: "patients", label: "Patient Count", type: num, align: "right", total: true },
      { key: "services", label: "Service Count", type: num, align: "right", total: true },
      { key: "gross", label: "Gross Income", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "net", label: "Net Income", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "dept-testwise-revenue",
    number: "2.13",
    name: "DEPARTMENT/TESTWISE REVENUE",
    category: "REVENUE",
    description: "Revenue grouped by department and test/service.",
    filters: [...RANGE, "department", "service", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "service", label: "Test/Service", type: str },
      { key: "quantity", label: "Quantity", type: num, align: "right", total: true },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "net", label: "Net", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "doctor-vs-dept",
    number: "2.14",
    name: "DOCT. WISE VS DEPT. WISE REPORT",
    category: "REVENUE",
    description: "Doctor wise revenue compared against department wise revenue.",
    filters: [...RANGE, "department", "doctor", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "doctor", label: "Doctor", type: str },
      { key: "department", label: "Department", type: str },
      { key: "patients", label: "Patients", type: num, align: "right", total: true },
      { key: "services", label: "Services", type: num, align: "right", total: true },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "net", label: "Net", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "ward-vs-dept",
    number: "2.15",
    name: "WARD VS DEPT. WISE REPORT",
    category: "REVENUE",
    description: "Ward wise revenue compared against department wise revenue.",
    filters: [...RANGE, "department", "ward", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "ward", label: "Ward", type: str },
      { key: "department", label: "Department", type: str },
      { key: "patients", label: "Patients", type: num, align: "right", total: true },
      { key: "services", label: "Services", type: num, align: "right", total: true },
      { key: "revenue", label: "Revenue", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "dept-vs-clinical",
    number: "2.16",
    name: "DEPT WISE VS CLINICAL DEP REPORT",
    category: "REVENUE",
    description: "Operational department revenue compared with clinical department revenue.",
    filters: [...RANGE, "department", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "opRevenue", label: "Op Revenue", type: money, align: "right", total: true },
      { key: "clinicalRevenue", label: "Clinical Revenue", type: money, align: "right", total: true },
      { key: "difference", label: "Difference", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "account-revenue-tally",
    number: "2.17",
    name: "ACCOUNT REVENUE TALLY REPORT",
    category: "REVENUE",
    description: "Journal tallies by account with debit, credit, revenue, adjustments and balance.",
    filters: [...RANGE, "account"],
    audience: "FINANCE",
    columns: [
      { key: "account", label: "Account", type: str },
      { key: "transactions", label: "Transactions", type: num, align: "right", total: true },
      { key: "debit", label: "Debit", type: money, align: "right", total: true },
      { key: "credit", label: "Credit", type: money, align: "right", total: true },
      { key: "revenue", label: "Revenue", type: money, align: "right", total: true },
      { key: "adjustment", label: "Adjustment", type: money, align: "right", total: true },
      { key: "balance", label: "Balance", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "indoor-treatment-summary",
    number: "2.18",
    name: "INDOOR TREATMENT SUMMARY",
    category: "REVENUE",
    description: "Summary of IPD treatment charges, payments and outstanding per patient.",
    filters: [...RANGE, "department", "ward", "doctor", "patient"],
    audience: "FINANCE",
    columns: [
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "admissionNumber", label: "Admission", type: str },
      { key: "admissionDate", label: "Admission Date", type: date },
      { key: "ward", label: "Ward", type: str },
      { key: "bed", label: "Bed", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "service", label: "Treatment/Service", type: str },
      { key: "charges", label: "Charges", type: money, align: "right", total: true },
      { key: "payment", label: "Payment", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "patient-wise-revenue",
    number: "2.507",
    name: "PATIENT WISE REVENUE REPORT",
    category: "REVENUE",
    description: "Revenue generated per patient with bill and service details.",
    filters: [...RANGE, "department", "doctor", "patient", "search"],
    audience: "FINANCE",
    columns: [
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "issuedDate", label: "Date", type: date },
      { key: "department", label: "Department", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "service", label: "Service", type: str },
      { key: "invoiceNumber", label: "Bill", type: str },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "net", label: "Net", type: money, align: "right", total: true },
      { key: "paid", label: "Paid", type: money, align: "right", total: true },
      { key: "outstanding", label: "Outstanding", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "materialized-view",
    number: "2.511",
    name: "MATERIALIZED VIEW REPORT",
    category: "REVENUE",
    description: "Configurable reporting datasets refreshed live from transactional data.",
    filters: [...RANGE],
    audience: "FINANCE",
    columns: [
      { key: "view", label: "View Name", type: str },
      { key: "description", label: "Description", type: str },
      { key: "lastRefreshed", label: "Last Refreshed", type: str },
      { key: "rows", label: "Row Count", type: num, align: "right" },
      { key: "data", label: "Data", type: str },
    ],
  }),

  def({
    id: "bank-deposit",
    number: "2.513",
    name: "BANK DEPOSIT REPORT",
    category: "REVENUE",
    description: "Bank deposits and bank-mode collections.",
    filters: [...RANGE, "branch", "userId", "search"],
    audience: "FINANCE",
    columns: [
      { key: "paidAt", label: "Date", type: date },
      { key: "depositNumber", label: "Deposit Number", type: str },
      { key: "bank", label: "Bank", type: str },
      { key: "account", label: "Account", type: str },
      { key: "amount", label: "Amount", type: money, align: "right", total: true },
      { key: "reference", label: "Deposit Reference", type: str },
      { key: "receivedBy", label: "User", type: str },
      { key: "status", label: "Status", type: str },
    ],
  }),

  def({
    id: "indoor-income",
    number: "2.514",
    name: "INDOOR INCOME REPORT",
    category: "REVENUE",
    description: "Income from indoor/IPD services.",
    filters: [...RANGE, "department", "ward", "doctor", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "issuedDate", label: "Date", type: date },
      { key: "department", label: "Department", type: str },
      { key: "ward", label: "Ward", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "service", label: "Service", type: str },
      { key: "amount", label: "Amount", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "outdoor-income",
    number: "2.515",
    name: "OUTDOOR INCOME REPORT",
    category: "REVENUE",
    description: "Income from outdoor/OPD services.",
    filters: [...RANGE, "department", "doctor", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "issuedDate", label: "Date", type: date },
      { key: "department", label: "Department", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "service", label: "Service", type: str },
      { key: "amount", label: "Amount", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "user-wise-collection",
    number: "2.516",
    name: "USER WISE COLLECTION PATIENT WISE",
    category: "REVENUE",
    description: "Collections recorded per cashier/user against each patient.",
    filters: [...RANGE, "branch", "paymentMode", "userId", "patient"],
    audience: "FINANCE",
    columns: [
      { key: "receivedBy", label: "User/Cashier", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "paymentNumber", label: "Bill/Receipt", type: str },
      { key: "paidAt", label: "Date", type: date },
      { key: "method", label: "Payment Mode", type: str },
      { key: "collection", label: "Collection", type: money, align: "right", total: true },
      { key: "refund", label: "Refund", type: money, align: "right", total: true },
      { key: "net", label: "Net Collection", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "revenue-statement",
    number: "2.517",
    name: "REVENUE STATEMENT",
    category: "REVENUE",
    description: "Detailed revenue statement with running balance.",
    filters: [...RANGE, "department", "doctor", "patient", "paymentMode", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "transaction", label: "Transaction", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "reference", label: "Bill/Receipt", type: str },
      { key: "department", label: "Department", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "account", label: "Account", type: str },
      { key: "paymentMode", label: "Payment Mode", type: str },
      { key: "debit", label: "Debit", type: money, align: "right", total: true },
      { key: "credit", label: "Credit", type: money, align: "right", total: true },
      { key: "balance", label: "Balance", type: money, align: "right" },
    ],
  }),

  def({
    id: "service-wise-income",
    number: "2.518",
    name: "SERVICE WISE INCOME",
    category: "REVENUE",
    description: "Income grouped by service with quantity and net.",
    filters: [...RANGE, "department", "service", "branch"],
    audience: "FINANCE",
    columns: [
      { key: "service", label: "Service", type: str },
      { key: "department", label: "Department", type: str },
      { key: "quantity", label: "Quantity", type: num, align: "right", total: true },
      { key: "gross", label: "Gross", type: money, align: "right", total: true },
      { key: "discount", label: "Discount", type: money, align: "right", total: true },
      { key: "refund", label: "Refund", type: money, align: "right", total: true },
      { key: "net", label: "Net Income", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "srl-report",
    number: "2.519",
    name: "SRL REPORT",
    category: "REVENUE",
    description: "Laboratory billing and testing summary.",
    filters: [...RANGE, "department", "doctor", "patient", "status"],
    audience: "FINANCE",
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "orderNumber", label: "Order No", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "test", label: "Test", type: str },
      { key: "category", label: "Category", type: str },
      { key: "amount", label: "Bill Amount", type: money, align: "right", total: true },
      { key: "paid", label: "Payment", type: money, align: "right", total: true },
      { key: "status", label: "Status", type: str },
    ],
  }),

  def({
    id: "operation-report",
    number: "2.520",
    name: "OPERATION REPORT",
    category: "REVENUE",
    description: "Operation theatre cases with procedure, surgeon and billing status.",
    filters: [...RANGE, "department", "doctor", "status"],
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "procedureName", label: "Procedure/Operation", type: str },
      { key: "surgeon", label: "Surgeon", type: str },
      { key: "department", label: "Department", type: str },
      { key: "otRoom", label: "OT", type: str },
      { key: "charges", label: "Charges", type: money, align: "right", total: true },
      { key: "billing", label: "Billing", type: money, align: "right", total: true },
      { key: "payment", label: "Payment", type: money, align: "right", total: true },
      { key: "status", label: "Status", type: str },
    ],
  }),
];

export const STATISTICS_REPORTS: ReportDefinition[] = [
  def({
    id: "dept-wise-stats",
    number: "2.100",
    name: "DEPARTMENT WISE STATISTICS REPORT",
    category: "STATISTICS",
    description: "Patient statistics per department.",
    filters: [...RANGE, "department", "doctor"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "totalPatients", label: "Total Patients", type: num, align: "right", total: true },
      { key: "newPatients", label: "New Patients", type: num, align: "right", total: true },
      { key: "followups", label: "Follow-up", type: num, align: "right", total: true },
      { key: "male", label: "Male", type: num, align: "right", total: true },
      { key: "female", label: "Female", type: num, align: "right", total: true },
      { key: "opd", label: "OPD", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD", type: num, align: "right", total: true },
      { key: "totalServices", label: "Total Services", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "date-day-wise-stats",
    number: "2.101",
    name: "DATE/DAY WISE STATISTICS REPORT",
    category: "STATISTICS",
    description: "Daily patient and visit statistics.",
    filters: [...RANGE, "department"],
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "newPatients", label: "New Patients", type: num, align: "right", total: true },
      { key: "returning", label: "Returning", type: num, align: "right", total: true },
      { key: "opd", label: "OPD", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD", type: num, align: "right", total: true },
      { key: "emergency", label: "Emergency", type: num, align: "right", total: true },
      { key: "total", label: "Total", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "month-wise-stats",
    number: "2.102",
    name: "MONTH WISE STATISTICS REPORT",
    category: "STATISTICS",
    description: "Monthly patient, admission, discharge and revenue statistics.",
    filters: [...RANGE, "month", "year", "department"],
    columns: [
      { key: "month", label: "Month", type: str },
      { key: "patients", label: "Patients", type: num, align: "right", total: true },
      { key: "opd", label: "OPD", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD", type: num, align: "right", total: true },
      { key: "emergency", label: "Emergency", type: num, align: "right", total: true },
      { key: "admissions", label: "Admissions", type: num, align: "right", total: true },
      { key: "discharges", label: "Discharges", type: num, align: "right", total: true },
      { key: "revenue", label: "Revenue", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "geographical-stats",
    number: "2.103",
    name: "GEOGRAPHICAL STATISTICS REPORT",
    category: "STATISTICS",
    description: "Patient distribution by country, province, district and city.",
    filters: [...RANGE],
    columns: [
      { key: "country", label: "Country", type: str },
      { key: "province", label: "State", type: str },
      { key: "district", label: "District", type: str },
      { key: "city", label: "City", type: str },
      { key: "count", label: "Patients", type: num, align: "right", total: true },
      { key: "percent", label: "Percentage", type: str },
    ],
  }),

  def({
    id: "dept-age-classified",
    number: "2.104",
    name: "DEPT. WISE AGE CLASSIFIED STATISTICS REPORT",
    category: "STATISTICS",
    description: "Patients grouped by department, age group and gender.",
    filters: [...RANGE, "department", "ageGroup"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "ageGroup", label: "Age Group", type: str },
      { key: "male", label: "Male", type: num, align: "right", total: true },
      { key: "female", label: "Female", type: num, align: "right", total: true },
      { key: "other", label: "Other", type: num, align: "right", total: true },
      { key: "total", label: "Patient Count", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "dept-wise-stats-ip",
    number: "2.106",
    name: "DEPARTMENT WISE STATISTICS REPORT (IP)",
    category: "STATISTICS",
    description: "IPD-specific department statistics.",
    filters: [...RANGE, "department", "ward"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "admissions", label: "Admissions", type: num, align: "right", total: true },
      { key: "discharges", label: "Discharges", type: num, align: "right", total: true },
      { key: "patients", label: "Patients", type: num, align: "right", total: true },
      { key: "avgStay", label: "Average Stay (days)", type: num },
      { key: "bedUsage", label: "Bed Usage", type: num, align: "right", total: true },
      { key: "occupancy", label: "Occupancy %", type: str },
    ],
  }),

  def({
    id: "geographical-stats-ip",
    number: "2.108",
    name: "GEOGRAPHICAL STATISTICS REPORT (IP)",
    category: "STATISTICS",
    description: "IPD patient distribution by geography.",
    filters: [...RANGE],
    columns: [
      { key: "country", label: "Country", type: str },
      { key: "province", label: "State", type: str },
      { key: "district", label: "District", type: str },
      { key: "city", label: "City", type: str },
      { key: "count", label: "Patients", type: num, align: "right", total: true },
      { key: "percent", label: "Percentage", type: str },
    ],
  }),

  def({
    id: "dept-age-classified-ip",
    number: "2.109",
    name: "DEPT. WISE AGE CLASSIFIED STATISTICS REPORT (IP)",
    category: "STATISTICS",
    description: "IPD patients grouped by department, age group and gender.",
    filters: [...RANGE, "department", "ageGroup"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "ageGroup", label: "Age Group", type: str },
      { key: "male", label: "Male", type: num, align: "right", total: true },
      { key: "female", label: "Female", type: num, align: "right", total: true },
      { key: "total", label: "Patient Count", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "patient-analysis",
    number: "2.110",
    name: "PATIENT ANALYSIS",
    category: "STATISTICS",
    description: "Comprehensive patient analytics by department.",
    filters: [...RANGE, "department", "doctor", "gender", "ageGroup"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "total", label: "Total Patients", type: num, align: "right", total: true },
      { key: "newPatients", label: "New", type: num, align: "right", total: true },
      { key: "returning", label: "Returning", type: num, align: "right", total: true },
      { key: "male", label: "Male", type: num, align: "right", total: true },
      { key: "female", label: "Female", type: num, align: "right", total: true },
      { key: "opd", label: "OPD", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD", type: num, align: "right", total: true },
      { key: "emergency", label: "Emergency", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "er-statistics",
    number: "2.111",
    name: "ER STATISTICS REPORT",
    category: "STATISTICS",
    description: "Emergency room visits, disposition and admission statistics.",
    filters: [...RANGE, "department"],
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "patient", label: "Patient", type: str },
      { key: "age", label: "Age", type: num },
      { key: "gender", label: "Gender", type: str },
      { key: "chiefComplaint", label: "Diagnosis", type: str },
      { key: "triageLevel", label: "Triage", type: str },
      { key: "admitted", label: "Admission", type: str },
      { key: "disposition", label: "Disposition", type: str },
    ],
  }),

  def({
    id: "dept-census",
    number: "2.112",
    name: "DEPARTMENT WISE CENSUS REPORT",
    category: "STATISTICS",
    description: "Current patient census grouped by department.",
    filters: [...RANGE, "department", "ward"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "patients", label: "Patients (Census)", type: num, align: "right", total: true },
      { key: "bedsOccupied", label: "Beds Occupied", type: num, align: "right", total: true },
      { key: "ward", label: "Ward", type: str },
      { key: "male", label: "Male", type: num, align: "right", total: true },
      { key: "female", label: "Female", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "dept-census-new",
    number: "2.113",
    name: "DEPARTMENT WISE CENSUS REPORT NEW",
    category: "STATISTICS",
    description: "Updated census format with gender and occupancy detail.",
    filters: [...RANGE, "department", "ward"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "totalBeds", label: "Total Beds", type: num, align: "right", total: true },
      { key: "occupied", label: "Occupied", type: num, align: "right", total: true },
      { key: "available", label: "Available", type: num, align: "right", total: true },
      { key: "patients", label: "Patients", type: num, align: "right", total: true },
      { key: "male", label: "Male", type: num, align: "right", total: true },
      { key: "female", label: "Female", type: num, align: "right", total: true },
      { key: "occupancyPct", label: "Occupancy %", type: str },
    ],
  }),

  def({
    id: "patient-analysis-doctor",
    number: "2.114",
    name: "PATIENT ANALYSIS",
    category: "STATISTICS",
    description: "Patient analysis by doctor (separate definition from 2.110).",
    filters: [...RANGE, "department", "doctor", "gender"],
    columns: [
      { key: "doctor", label: "Doctor", type: str },
      { key: "department", label: "Department", type: str },
      { key: "newPatients", label: "New", type: num, align: "right", total: true },
      { key: "returning", label: "Returning", type: num, align: "right", total: true },
      { key: "opd", label: "OPD", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD", type: num, align: "right", total: true },
      { key: "total", label: "Total Patients", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "periodical-inpatient-stats",
    number: "2.115",
    name: "PERIODICAL INPATIENT STATS.",
    category: "STATISTICS",
    description: "Inpatient statistics over a custom period.",
    filters: [...RANGE, "department", "ward"],
    columns: [
      { key: "department", label: "Department", type: str },
      { key: "admissions", label: "Admissions", type: num, align: "right", total: true },
      { key: "discharges", label: "Discharges", type: num, align: "right", total: true },
      { key: "deaths", label: "Deaths", type: num, align: "right", total: true },
      { key: "transfers", label: "Transfers", type: num, align: "right", total: true },
      { key: "avgStay", label: "Average Stay", type: num },
      { key: "occupancy", label: "Occupancy %", type: str },
      { key: "bedDays", label: "Bed Days", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "discharge-record-sheet",
    number: "2.116",
    name: "DISCHARGE RECORD SHEET",
    category: "STATISTICS",
    description: "Discharged patient records with billing status.",
    filters: [...RANGE, "department", "ward", "doctor", "status"],
    columns: [
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "admissionNumber", label: "Admission No", type: str },
      { key: "admissionDate", label: "Admission Date", type: date },
      { key: "dischargeDate", label: "Discharge Date", type: date },
      { key: "ward", label: "Ward", type: str },
      { key: "bed", label: "Bed", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "diagnosis", label: "Diagnosis", type: str },
      { key: "dischargeType", label: "Discharge Type", type: str },
      { key: "billingStatus", label: "Billing Status", type: str },
    ],
  }),

  def({
    id: "patient-detail-opd",
    number: "2.543",
    name: "PATIENT DETAIL OPD",
    category: "STATISTICS",
    description: "Detailed OPD patient visits.",
    filters: [...RANGE, "department", "doctor", "patient"],
    columns: [
      { key: "date", label: "Date", type: date },
      { key: "uhid", label: "UHID", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "department", label: "Department", type: str },
      { key: "type", label: "Visit", type: str },
      { key: "diagnosis", label: "Diagnosis", type: str },
      { key: "services", label: "Services", type: num, align: "right", total: true },
      { key: "billing", label: "Billing", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "patient-detail-ipd",
    number: "2.544",
    name: "PATIENT DETAIL IPD",
    category: "STATISTICS",
    description: "Detailed IPD patient admissions.",
    filters: [...RANGE, "department", "ward", "doctor", "patient"],
    columns: [
      { key: "patient", label: "Patient", type: str },
      { key: "uhid", label: "UHID", type: str },
      { key: "admissionNumber", label: "Admission", type: str },
      { key: "admissionDate", label: "Admission", type: date },
      { key: "ward", label: "Ward", type: str },
      { key: "bed", label: "Bed", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "diagnosis", label: "Diagnosis", type: str },
      { key: "services", label: "Services", type: num, align: "right", total: true },
      { key: "charges", label: "Charges", type: money, align: "right", total: true },
      { key: "dischargeDate", label: "Discharge", type: date },
    ],
  }),

  def({
    id: "bed-occupancy",
    number: "2.545",
    name: "BED OCCUPANCY REPORT",
    category: "STATISTICS",
    description: "Current bed occupancy by ward and bed.",
    filters: [...RANGE, "ward", "bed", "status"],
    columns: [
      { key: "ward", label: "Ward", type: str },
      { key: "bed", label: "Bed", type: str },
      { key: "bedType", label: "Bed Type", type: str },
      { key: "status", label: "Status", type: str },
      { key: "patient", label: "Patient", type: str },
      { key: "admissionDate", label: "Admission Date", type: date },
      { key: "duration", label: "Occupancy Days", type: num },
    ],
  }),

  def({
    id: "bed-analysis",
    number: "2.546",
    name: "BED ANALYSIS REPORT",
    category: "STATISTICS",
    description: "Bed utilization and occupancy analysis.",
    filters: [...RANGE, "ward", "bed"],
    columns: [
      { key: "ward", label: "Ward", type: str },
      { key: "bed", label: "Bed", type: str },
      { key: "occupiedDays", label: "Occupancy", type: num, align: "right", total: true },
      { key: "utilization", label: "Utilization %", type: str },
      { key: "transfers", label: "Transfers", type: num, align: "right", total: true },
      { key: "avgOccupancy", label: "Avg Occupancy", type: num },
      { key: "available", label: "Available Capacity", type: num },
    ],
  }),

  def({
    id: "service-wise-stats",
    number: "2.547",
    name: "SERVICE WISE STATISTICS REPORT",
    category: "STATISTICS",
    description: "Service usage and revenue statistics.",
    filters: [...RANGE, "department", "service"],
    columns: [
      { key: "service", label: "Service", type: str },
      { key: "department", label: "Department", type: str },
      { key: "quantity", label: "Quantity", type: num, align: "right", total: true },
      { key: "patients", label: "Patients", type: num, align: "right", total: true },
      { key: "revenue", label: "Revenue", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "monthly-doctor-wise",
    number: "2.548",
    name: "MONTHLY DOCTOR WISE REPORT",
    category: "STATISTICS",
    description: "Monthly doctor activity and revenue.",
    filters: [...RANGE, "month", "year", "department", "doctor"],
    columns: [
      { key: "month", label: "Month", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "department", label: "Department", type: str },
      { key: "patients", label: "Patient Count", type: num, align: "right", total: true },
      { key: "opd", label: "OPD", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD", type: num, align: "right", total: true },
      { key: "services", label: "Services", type: num, align: "right", total: true },
      { key: "revenue", label: "Revenue", type: money, align: "right", total: true },
    ],
  }),

  def({
    id: "doc-wise-patient-total",
    number: "2.549",
    name: "DOC. WISE PATIENT TOTAL",
    category: "STATISTICS",
    description: "Patient totals per doctor.",
    filters: [...RANGE, "department", "doctor"],
    columns: [
      { key: "doctor", label: "Doctor", type: str },
      { key: "department", label: "Department", type: str },
      { key: "opd", label: "OPD Patients", type: num, align: "right", total: true },
      { key: "ipd", label: "IPD Patients", type: num, align: "right", total: true },
      { key: "newPatients", label: "New Patients", type: num, align: "right", total: true },
      { key: "followups", label: "Follow-up", type: num, align: "right", total: true },
      { key: "total", label: "Total Patients", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "age-wise-opd",
    number: "2.550",
    name: "AGE WISE OPD REPORT NEW",
    category: "STATISTICS",
    description: "OPD patients by age group, gender, department and doctor.",
    filters: [...RANGE, "department", "doctor", "ageGroup"],
    columns: [
      { key: "ageGroup", label: "Age Group", type: str },
      { key: "gender", label: "Gender", type: str },
      { key: "department", label: "Department", type: str },
      { key: "doctor", label: "Doctor", type: str },
      { key: "count", label: "Patient Count", type: num, align: "right", total: true },
    ],
  }),

  def({
    id: "doctor-wise-referral",
    number: "2.551",
    name: "DOCTOR WISE REFERRAL",
    category: "STATISTICS",
    description: "Referrals recorded per referring doctor.",
    filters: [...RANGE, "department", "doctor", "status"],
    columns: [
      { key: "referringDoctor", label: "Referring Doctor", type: str },
      { key: "patient", label: "Referred Patient", type: str },
      { key: "date", label: "Referral Date", type: date },
      { key: "department", label: "Department", type: str },
      { key: "receivingDoctor", label: "Receiving Doctor", type: str },
      { key: "service", label: "Service", type: str },
      { key: "status", label: "Status", type: str },
      { key: "count", label: "Count", type: num, align: "right", total: true },
    ],
  }),
];

export const FRACTION_REPORTS: ReportDefinition[] = [];

export const CATEGORIES: ReportCategory[] = [
  { id: "REVENUE", key: "1.1", label: "1.1 - REVENUE REPORT", reports: REVENUE_REPORTS },
  { id: "STATISTICS", key: "1.2", label: "1.2 - STATISTICS REPORT", reports: STATISTICS_REPORTS },
  { id: "FRACTION", key: "1.3", label: "1.3 - FRACTION REPORT", reports: FRACTION_REPORTS },
];

const ALL = new Map<string, ReportDefinition>();
for (const c of CATEGORIES) {
  for (const r of c.reports) ALL.set(r.id, r);
}

export function getReportDefinition(id: string): ReportDefinition | undefined {
  return ALL.get(id);
}

export function getReportDefinitions(): ReportDefinition[] {
  return [...ALL.values()];
}

export const AGE_GROUPS = ["0-5", "6-12", "13-18", "19-30", "31-45", "46-60", "61+"];

export function ageGroupOf(birth: Date | null | undefined, ref = new Date()): string | null {
  if (!birth) return null;
  const b = new Date(birth);
  if (isNaN(b.getTime())) return null;
  const age = Math.floor((ref.getTime() - b.getTime()) / (365.25 * 24 * 3600 * 1000));
  if (age <= 5) return "0-5";
  if (age <= 12) return "6-12";
  if (age <= 18) return "13-18";
  if (age <= 30) return "19-30";
  if (age <= 45) return "31-45";
  if (age <= 60) return "46-60";
  return "61+";
}
