import { PermissionAction, UserRole } from '../enums';

export const ROLE_PERMISSIONS: Record<UserRole, PermissionAction[]> = {
  [UserRole.PLATFORM_SUPER_ADMIN]: Object.values(PermissionAction),
  [UserRole.HOSPITAL_ADMIN]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.REFUND,
    PermissionAction.DISCOUNT,
    PermissionAction.SETTLE,
    PermissionAction.ADMINISTER,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
    PermissionAction.CONFIGURE,
  ],
  [UserRole.HOSPITAL_OWNER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.REFUND,
    PermissionAction.DISCOUNT,
    PermissionAction.SETTLE,
    PermissionAction.ADMINISTER,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
    PermissionAction.CONFIGURE,
  ],
  [UserRole.DEPARTMENT_HEAD]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  [UserRole.RECEPTIONIST]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.DISCOUNT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.VERIFY,
  ],
  [UserRole.RECEPTION_SUPERVISOR]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.DISCOUNT,
  ],
  [UserRole.DOCTOR]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.SIGN,
    PermissionAction.VERIFY,
  ],
  [UserRole.NURSE]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.WARD_INCHARGE]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
  ],
  [UserRole.LAB_TECHNICIAN]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.PATHOLOGIST]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  [UserRole.RADIOLOGIST]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  [UserRole.RADIOLOGY_TECHNICIAN]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.PHARMACIST]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
    PermissionAction.ADMINISTER,
  ],
  [UserRole.FINANCE_MANAGER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.REFUND,
    PermissionAction.DISCOUNT,
    PermissionAction.SETTLE,
    PermissionAction.ADMINISTER,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  [UserRole.INSURANCE_OFFICER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
  ],
  [UserRole.HR_MANAGER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.ADMINISTER,
  ],
  [UserRole.INVENTORY_MANAGER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
  ],
  [UserRole.STORE_KEEPER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.PURCHASE_OFFICER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
  ],
  [UserRole.OT_TECHNICIAN]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.OT_NURSE]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.ANESTHETIST]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  [UserRole.ICU_STAFF]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.EMERGENCY_STAFF]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.AMBULANCE_STAFF]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
  ],
  [UserRole.BLOOD_BANK_STAFF]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.VERIFY,
  ],
  [UserRole.BIOMEDICAL_ENGINEER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
  ],
  [UserRole.IT_ADMIN]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.ADMINISTER,
    PermissionAction.CONFIGURE,
  ],
  [UserRole.QUALITY_MANAGER]: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.VERIFY,
  ],
  [UserRole.AUDITOR]: [
    PermissionAction.VIEW,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
  ],
  [UserRole.PATIENT]: [
    PermissionAction.VIEW,
    PermissionAction.PRINT,
  ],
};

export const RESOURCE_PERMISSIONS = {
  PATIENT: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
  ],
  APPOINTMENT: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.PRINT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
  ],
  ENCOUNTER: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.SIGN,
    PermissionAction.VERIFY,
  ],
  PRESCRIPTION: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.SIGN,
    PermissionAction.VERIFY,
  ],
  LAB_ORDER: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  RADIOLOGY_ORDER: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.VERIFY,
    PermissionAction.SIGN,
  ],
  ADMISSION: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
  ],
  BED: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
  ],
  INVOICE: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.REFUND,
    PermissionAction.DISCOUNT,
    PermissionAction.SETTLE,
  ],
  PAYMENT: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.REFUND,
    PermissionAction.SETTLE,
  ],
  INVENTORY: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
  ],
  PURCHASE: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
  ],
  DOCTOR_SHARE: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
  ],
  HR: [
    PermissionAction.VIEW,
    PermissionAction.CREATE,
    PermissionAction.EDIT,
    PermissionAction.DELETE,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
    PermissionAction.APPROVE,
    PermissionAction.REJECT,
    PermissionAction.ADMINISTER,
  ],
  SETTINGS: [
    PermissionAction.VIEW,
    PermissionAction.EDIT,
    PermissionAction.CONFIGURE,
    PermissionAction.ADMINISTER,
  ],
  REPORTS: [
    PermissionAction.VIEW,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
  ],
  ANALYTICS: [
    PermissionAction.VIEW,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
  ],
  AUDIT_LOG: [
    PermissionAction.VIEW,
    PermissionAction.PRINT,
    PermissionAction.EXPORT,
  ],
} as const;

export function hasPermission(
  userRole: UserRole,
  action: PermissionAction,
  resource?: keyof typeof RESOURCE_PERMISSIONS
): boolean {
  const rolePermissions = ROLE_PERMISSIONS[userRole] || [];
  
  if (!rolePermissions.includes(action)) {
    return false;
  }

  if (resource) {
    const resourcePermissions = RESOURCE_PERMISSIONS[resource];
    if (resourcePermissions && !(resourcePermissions as readonly PermissionAction[]).includes(action)) {
      return false;
    }
  }

  return true;
}

export function getRolePermissions(role: UserRole): PermissionAction[] {
  return [...(ROLE_PERMISSIONS[role] || [])];
}

export function getResourcePermissions(resource: keyof typeof RESOURCE_PERMISSIONS): PermissionAction[] {
  return [...RESOURCE_PERMISSIONS[resource]];
}