export interface Icd10Entry {
  code: string;
  name: string;
  category: string;
}

export const ICD10_CATALOG: Icd10Entry[] = [
  {
    code: "A00.0",
    name: "Cholera due to Vibrio cholerae 01",
    category: "Infectious",
  },
  {
    code: "A09",
    name: "Infectious gastroenteritis and colitis",
    category: "Infectious",
  },
  { code: "A41.9", name: "Sepsis, unspecified", category: "Infectious" },
  {
    code: "B18.1",
    name: "Chronic viral hepatitis B without delta-agent",
    category: "Infectious",
  },
  { code: "B18.2", name: "Chronic viral hepatitis C", category: "Infectious" },
  {
    code: "B20",
    name: "Human immunodeficiency virus disease",
    category: "Infectious",
  },
  {
    code: "B34.2",
    name: "Coronavirus infection, unspecified",
    category: "Infectious",
  },
  {
    code: "C16.9",
    name: "Malignant neoplasm of stomach, unspecified",
    category: "Neoplasms",
  },
  {
    code: "C18.9",
    name: "Malignant neoplasm of colon, unspecified",
    category: "Neoplasms",
  },
  {
    code: "C34.9",
    name: "Malignant neoplasm of bronchus or lung, unspecified",
    category: "Neoplasms",
  },
  {
    code: "C50.9",
    name: "Malignant neoplasm of breast, unspecified",
    category: "Neoplasms",
  },
  {
    code: "C61",
    name: "Malignant neoplasm of prostate",
    category: "Neoplasms",
  },
  {
    code: "D63.8",
    name: "Anemia in other chronic diseases classified elsewhere",
    category: "Neoplasms",
  },
  { code: "D64.9", name: "Anemia, unspecified", category: "Blood" },
  { code: "E03.9", name: "Hypothyroidism, unspecified", category: "Endocrine" },
  {
    code: "E10.9",
    name: "Type 1 diabetes mellitus without complications",
    category: "Endocrine",
  },
  {
    code: "E11.9",
    name: "Type 2 diabetes mellitus without complications",
    category: "Endocrine",
  },
  { code: "E66.9", name: "Obesity, unspecified", category: "Endocrine" },
  { code: "E78.5", name: "Hyperlipidemia, unspecified", category: "Endocrine" },
  { code: "F03", name: "Unspecified dementia", category: "Mental" },
  { code: "F10.2", name: "Alcohol dependence", category: "Mental" },
  {
    code: "F32.9",
    name: "Major depressive disorder, single episode, unspecified",
    category: "Mental",
  },
  { code: "F41.1", name: "Generalized anxiety disorder", category: "Mental" },
  { code: "F41.9", name: "Anxiety disorder, unspecified", category: "Mental" },
  {
    code: "F43.9",
    name: "Reaction to severe stress, unspecified",
    category: "Mental",
  },
  { code: "G40.9", name: "Epilepsy, unspecified", category: "Neurological" },
  { code: "G43.9", name: "Migraine, unspecified", category: "Neurological" },
  { code: "H25.9", name: "Age-related cataract, unspecified", category: "Eye" },
  { code: "H52.1", name: "Myopia", category: "Eye" },
  { code: "H66.9", name: "Otitis media, unspecified", category: "Ear" },
  {
    code: "I10",
    name: "Essential (primary) hypertension",
    category: "Circulatory",
  },
  {
    code: "I20.9",
    name: "Angina pectoris, unspecified",
    category: "Circulatory",
  },
  {
    code: "I21.9",
    name: "Acute myocardial infarction, unspecified",
    category: "Circulatory",
  },
  {
    code: "I25.1",
    name: "Atherosclerotic heart disease",
    category: "Circulatory",
  },
  {
    code: "I25.9",
    name: "Chronic ischemic heart disease, unspecified",
    category: "Circulatory",
  },
  {
    code: "I48.9",
    name: "Atrial fibrillation and atrial flutter, unspecified",
    category: "Circulatory",
  },
  {
    code: "I50.9",
    name: "Heart failure, unspecified",
    category: "Circulatory",
  },
  {
    code: "I63.9",
    name: "Cerebral infarction, unspecified",
    category: "Circulatory",
  },
  {
    code: "I64",
    name: "Stroke, not specified as hemorrhage or infarction",
    category: "Circulatory",
  },
  {
    code: "I83.9",
    name: "Varicose veins of lower extremities without ulcer or inflammation",
    category: "Circulatory",
  },
  {
    code: "J00",
    name: "Acute nasopharyngitis (common cold)",
    category: "Respiratory",
  },
  {
    code: "J02.9",
    name: "Acute pharyngitis, unspecified",
    category: "Respiratory",
  },
  {
    code: "J03.9",
    name: "Acute tonsillitis, unspecified",
    category: "Respiratory",
  },
  {
    code: "J06.9",
    name: "Acute upper respiratory infection, unspecified",
    category: "Respiratory",
  },
  {
    code: "J18.9",
    name: "Pneumonia, unspecified organism",
    category: "Respiratory",
  },
  {
    code: "J20.9",
    name: "Acute bronchitis, unspecified",
    category: "Respiratory",
  },
  {
    code: "J30.4",
    name: "Allergic rhinitis, unspecified",
    category: "Respiratory",
  },
  {
    code: "J40",
    name: "Bronchitis, not specified as acute or chronic",
    category: "Respiratory",
  },
  {
    code: "J44.9",
    name: "Chronic obstructive pulmonary disease, unspecified",
    category: "Respiratory",
  },
  { code: "J45.9", name: "Asthma, unspecified", category: "Respiratory" },
  {
    code: "K21.0",
    name: "Gastro-esophageal reflux disease with esophagitis",
    category: "Digestive",
  },
  { code: "K29.7", name: "Gastritis, unspecified", category: "Digestive" },
  { code: "K30", name: "Functional dyspepsia", category: "Digestive" },
  {
    code: "K35.80",
    name: "Unspecified acute appendicitis",
    category: "Digestive",
  },
  {
    code: "K52.9",
    name: "Noninfective gastroenteritis and colitis, unspecified",
    category: "Digestive",
  },
  {
    code: "K57.3",
    name: "Diverticulosis of large intestine without perforation or abscess",
    category: "Digestive",
  },
  {
    code: "K70.3",
    name: "Alcoholic cirrhosis of liver",
    category: "Digestive",
  },
  {
    code: "K74.6",
    name: "Other and unspecified cirrhosis of liver",
    category: "Digestive",
  },
  { code: "K76.9", name: "Liver disease, unspecified", category: "Digestive" },
  { code: "L20.9", name: "Atopic dermatitis, unspecified", category: "Skin" },
  {
    code: "L23.9",
    name: "Allergic contact dermatitis, unspecified cause",
    category: "Skin",
  },
  { code: "L30.9", name: "Dermatitis, unspecified", category: "Skin" },
  {
    code: "M05.9",
    name: "Rheumatoid arthritis, unspecified",
    category: "Musculoskeletal",
  },
  {
    code: "M06.9",
    name: "Rheumatoid arthritis, unspecified (other)",
    category: "Musculoskeletal",
  },
  { code: "M10.9", name: "Gout, unspecified", category: "Musculoskeletal" },
  {
    code: "M17.9",
    name: "Gonarthrosis, unspecified",
    category: "Musculoskeletal",
  },
  {
    code: "M19.9",
    name: "Osteoarthritis, unspecified",
    category: "Musculoskeletal",
  },
  { code: "M25.5", name: "Pain in joint", category: "Musculoskeletal" },
  {
    code: "M48.06",
    name: "Spinal stenosis, lumbar region",
    category: "Musculoskeletal",
  },
  { code: "M54.5", name: "Low back pain", category: "Musculoskeletal" },
  { code: "M79.1", name: "Myalgia", category: "Musculoskeletal" },
  {
    code: "N18.9",
    name: "Chronic kidney disease, unspecified",
    category: "Genitourinary",
  },
  { code: "N20.0", name: "Calculus of kidney", category: "Genitourinary" },
  { code: "N30.9", name: "Cystitis, unspecified", category: "Genitourinary" },
  {
    code: "N39.0",
    name: "Urinary tract infection, site not specified",
    category: "Genitourinary",
  },
  {
    code: "N40",
    name: "Benign prostatic hyperplasia",
    category: "Genitourinary",
  },
  {
    code: "O20.9",
    name: "Hemorrhage in early pregnancy, unspecified",
    category: "Pregnancy",
  },
  {
    code: "O80",
    name: "Encounter for full-term uncomplicated delivery",
    category: "Pregnancy",
  },
  {
    code: "P07.3",
    name: "Preterm newborn, 28 to 31 weeks",
    category: "Perinatal",
  },
  {
    code: "P59.9",
    name: "Neonatal jaundice, unspecified",
    category: "Perinatal",
  },
  { code: "R05", name: "Cough", category: "Symptoms" },
  { code: "R06.0", name: "Dyspnea", category: "Symptoms" },
  { code: "R07.9", name: "Chest pain, unspecified", category: "Symptoms" },
  { code: "R10.9", name: "Unspecified abdominal pain", category: "Symptoms" },
  { code: "R11", name: "Nausea and vomiting", category: "Symptoms" },
  { code: "R17", name: "Unspecified jaundice", category: "Symptoms" },
  { code: "R19.7", name: "Diarrhea, unspecified", category: "Symptoms" },
  {
    code: "R21",
    name: "Rash and other nonspecific skin eruption",
    category: "Symptoms",
  },
  { code: "R31", name: "Hematuria", category: "Symptoms" },
  { code: "R42", name: "Dizziness and giddiness", category: "Symptoms" },
  { code: "R50.9", name: "Fever, unspecified", category: "Symptoms" },
  { code: "R51", name: "Headache", category: "Symptoms" },
  { code: "R53", name: "Malaise and fatigue", category: "Symptoms" },
  { code: "R55", name: "Syncope and collapse", category: "Symptoms" },
  { code: "R73.9", name: "Hyperglycemia, unspecified", category: "Symptoms" },
  {
    code: "R74.8",
    name: "Abnormal levels of other serum enzymes",
    category: "Symptoms",
  },
  {
    code: "R79.9",
    name: "Abnormal findings of blood chemistry, unspecified",
    category: "Symptoms",
  },
  {
    code: "S00.9",
    name: "Superficial injury of head, unspecified",
    category: "Injury",
  },
  {
    code: "S52.9",
    name: "Fracture of forearm, unspecified",
    category: "Injury",
  },
  { code: "S62.5", name: "Fracture of thumb", category: "Injury" },
  {
    code: "S72.0",
    name: "Fracture of head and neck of femur",
    category: "Injury",
  },
  {
    code: "S82.9",
    name: "Fracture of lower leg, unspecified",
    category: "Injury",
  },
  { code: "T14.9", name: "Injury, unspecified", category: "Injury" },
  { code: "T78.4", name: "Allergy, unspecified", category: "Injury" },
  {
    code: "Z00.00",
    name: "General adult medical examination",
    category: "Factors",
  },
  {
    code: "Z01.30",
    name: "Encounter for examination of blood pressure without abnormal findings",
    category: "Factors",
  },
  {
    code: "Z03.9",
    name: "Observation for suspected disease, unspecified",
    category: "Factors",
  },
  { code: "Z23", name: "Encounter for immunization", category: "Factors" },
  {
    code: "Z71.1",
    name: "Persons with feared health complaint in whom no diagnosis is made",
    category: "Factors",
  },
  {
    code: "Z85.9",
    name: "Personal history of malignant neoplasm, unspecified",
    category: "Factors",
  },
  {
    code: "Z96.6",
    name: "Presence of orthopedic joint implants",
    category: "Factors",
  },
];
