-- Appointment & follow-up lifecycle (spec §46/§47) — additive only.
-- Generated by hand from the working-tree schema.prisma changes; the legacy
-- snake_case drift in unrelated tables is intentionally NOT touched here.

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each adding only one value to the enum.


ALTER TYPE "AppointmentStatus" ADD VALUE 'DRAFT';
ALTER TYPE "AppointmentStatus" ADD VALUE 'PENDING_CONFIRMATION';
ALTER TYPE "AppointmentStatus" ADD VALUE 'IN_QUEUE';
ALTER TYPE "AppointmentStatus" ADD VALUE 'EXPIRED';
ALTER TYPE "AppointmentStatus" ADD VALUE 'REJECTED';
ALTER TYPE "AppointmentStatus" ADD VALUE 'DEFERRED';

-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each adding only one value to the enum.


ALTER TYPE "FollowUpStatus" ADD VALUE 'RECOMMENDED';
ALTER TYPE "FollowUpStatus" ADD VALUE 'DUE';
ALTER TYPE "FollowUpStatus" ADD VALUE 'SCHEDULED';
ALTER TYPE "FollowUpStatus" ADD VALUE 'UPCOMING';
ALTER TYPE "FollowUpStatus" ADD VALUE 'MISSED';
ALTER TYPE "FollowUpStatus" ADD VALUE 'OVERDUE';
ALTER TYPE "FollowUpStatus" ADD VALUE 'DEFERRED';
ALTER TYPE "FollowUpStatus" ADD VALUE 'NOT_REQUIRED';
ALTER TYPE "FollowUpStatus" ADD VALUE 'CLOSED';

-- AlterTable
ALTER TABLE "appointments" ADD COLUMN     "appointmentNumber" TEXT,
ADD COLUMN     "cancelledBy" TEXT,
ADD COLUMN     "checkedInBy" TEXT,
ADD COLUMN     "completedBy" TEXT,
ADD COLUMN     "confirmedAt" TIMESTAMP(3),
ADD COLUMN     "confirmedBy" TEXT,
ADD COLUMN     "followUpId" TEXT,
ADD COLUMN     "priority" TEXT NOT NULL DEFAULT 'NORMAL',
ADD COLUMN     "rescheduledFromId" TEXT,
ADD COLUMN     "rescheduledToId" TEXT,
ADD COLUMN     "startedAt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "follow_ups" ADD COLUMN     "appointmentId" TEXT,
ADD COLUMN     "cancellationReason" TEXT,
ADD COLUMN     "cancelledAt" TIMESTAMP(3),
ADD COLUMN     "cancelledBy" TEXT,
ADD COLUMN     "clinicalInstruction" TEXT,
ADD COLUMN     "closedAt" TIMESTAMP(3),
ADD COLUMN     "completedAt" TIMESTAMP(3),
ADD COLUMN     "completedBy" TEXT,
ADD COLUMN     "dueDate" TIMESTAMP(3),
ADD COLUMN     "followUpType" TEXT NOT NULL DEFAULT 'TREATMENT_REVIEW',
ADD COLUMN     "maximumDate" TIMESTAMP(3),
ADD COLUMN     "minimumDate" TIMESTAMP(3),
ADD COLUMN     "priority" TEXT NOT NULL DEFAULT 'NORMAL',
ADD COLUMN     "reason" TEXT,
ADD COLUMN     "recommendedDate" TIMESTAMP(3),
ADD COLUMN     "source" TEXT NOT NULL DEFAULT 'CLINICIAN_MANUAL';

-- CreateTable
CREATE TABLE "appointment_events" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "appointmentId" TEXT NOT NULL,
    "event" TEXT NOT NULL,
    "fromStatus" TEXT,
    "toStatus" TEXT,
    "actorId" TEXT,
    "actorRole" TEXT,
    "reason" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "appointment_events_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "follow_up_events" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "followUpId" TEXT NOT NULL,
    "event" TEXT NOT NULL,
    "fromStatus" TEXT,
    "toStatus" TEXT,
    "actorId" TEXT,
    "actorRole" TEXT,
    "reason" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "follow_up_events_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "appointment_events_appointmentId_idx" ON "appointment_events"("appointmentId");

-- CreateIndex
CREATE INDEX "appointment_events_tenantId_createdAt_idx" ON "appointment_events"("tenantId", "createdAt");

-- CreateIndex
CREATE INDEX "follow_up_events_followUpId_idx" ON "follow_up_events"("followUpId");

-- CreateIndex
CREATE INDEX "follow_up_events_tenantId_createdAt_idx" ON "follow_up_events"("tenantId", "createdAt");

-- CreateIndex
CREATE UNIQUE INDEX "appointments_appointmentNumber_key" ON "appointments"("appointmentNumber");

-- CreateIndex
CREATE INDEX "appointments_followUpId_idx" ON "appointments"("followUpId");

-- CreateIndex
CREATE INDEX "follow_ups_dueDate_idx" ON "follow_ups"("dueDate");

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_followUpId_fkey" FOREIGN KEY ("followUpId") REFERENCES "follow_ups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointments" ADD CONSTRAINT "appointments_rescheduledFromId_fkey" FOREIGN KEY ("rescheduledFromId") REFERENCES "appointments"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_events" ADD CONSTRAINT "appointment_events_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "appointment_events" ADD CONSTRAINT "appointment_events_appointmentId_fkey" FOREIGN KEY ("appointmentId") REFERENCES "appointments"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follow_up_events" ADD CONSTRAINT "follow_up_events_tenantId_fkey" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "follow_up_events" ADD CONSTRAINT "follow_up_events_followUpId_fkey" FOREIGN KEY ("followUpId") REFERENCES "follow_ups"("id") ON DELETE CASCADE ON UPDATE CASCADE;
