export enum UserRole {
  PLATFORM_SUPER_ADMIN = 'PLATFORM_SUPER_ADMIN',
  HOSPITAL_ADMIN = 'HOSPITAL_ADMIN',
  HOSPITAL_OWNER = 'HOSPITAL_OWNER',
  DEPARTMENT_HEAD = 'DEPARTMENT_HEAD',
  RECEPTIONIST = 'RECEPTIONIST',
  RECEPTION_SUPERVISOR = 'RECEPTION_SUPERVISOR',
  DOCTOR = 'DOCTOR',
  NURSE = 'NURSE',
  WARD_INCHARGE = 'WARD_INCHARGE',
  LAB_TECHNICIAN = 'LAB_TECHNICIAN',
  PATHOLOGIST = 'PATHOLOGIST',
  RADIOLOGIST = 'RADIOLOGIST',
  RADIOLOGY_TECHNICIAN = 'RADIOLOGY_TECHNICIAN',
  PHARMACIST = 'PHARMACIST',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  INSURANCE_OFFICER = 'INSURANCE_OFFICER',
  HR_MANAGER = 'HR_MANAGER',
  INVENTORY_MANAGER = 'INVENTORY_MANAGER',
  STORE_KEEPER = 'STORE_KEEPER',
  PURCHASE_OFFICER = 'PURCHASE_OFFICER',
  OT_TECHNICIAN = 'OT_TECHNICIAN',
  OT_NURSE = 'OT_NURSE',
  ANESTHETIST = 'ANESTHETIST',
  ICU_STAFF = 'ICU_STAFF',
  EMERGENCY_STAFF = 'EMERGENCY_STAFF',
  AMBULANCE_STAFF = 'AMBULANCE_STAFF',
  BLOOD_BANK_STAFF = 'BLOOD_BANK_STAFF',
  BIOMEDICAL_ENGINEER = 'BIOMEDICAL_ENGINEER',
  IT_ADMIN = 'IT_ADMIN',
  QUALITY_MANAGER = 'QUALITY_MANAGER',
  AUDITOR = 'AUDITOR',
  PATIENT = 'PATIENT',
}

export enum PermissionAction {
  VIEW = 'VIEW',
  CREATE = 'CREATE',
  EDIT = 'EDIT',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  PRINT = 'PRINT',
  EXPORT = 'EXPORT',
  REFUND = 'REFUND',
  DISCOUNT = 'DISCOUNT',
  SETTLE = 'SETTLE',
  ADMINISTER = 'ADMINISTER',
  VERIFY = 'VERIFY',
  SIGN = 'SIGN',
  CONFIGURE = 'CONFIGURE',
}

export enum TenantStatus {
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  ARCHIVED = 'ARCHIVED',
  TRIAL = 'TRIAL',
  EXPIRED = 'EXPIRED',
}

export enum SubscriptionPlan {
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE',
  CUSTOM = 'CUSTOM',
}

export enum PatientType {
  GENERAL = 'GENERAL',
  FOREIGN = 'FOREIGN',
  STAFF = 'STAFF',
  STAFF_RELATIVE = 'STAFF_RELATIVE',
  CORPORATE = 'CORPORATE',
  INSURANCE = 'INSURANCE',
  MEMBER = 'MEMBER',
  EMERGENCY = 'EMERGENCY',
}

export enum AppointmentStatus {
  REQUESTED = 'REQUESTED',
  CONFIRMED = 'CONFIRMED',
  CHECKED_IN = 'CHECKED_IN',
  WAITING = 'WAITING',
  IN_CONSULTATION = 'IN_CONSULTATION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum BedStatus {
  AVAILABLE = 'AVAILABLE',
  RESERVED = 'RESERVED',
  OCCUPIED = 'OCCUPIED',
  CLEANING = 'CLEANING',
  MAINTENANCE = 'MAINTENANCE',
  BLOCKED = 'BLOCKED',
}

export enum BedType {
  GENERAL = 'GENERAL',
  SEMI_PRIVATE = 'SEMI_PRIVATE',
  PRIVATE = 'PRIVATE',
  DELUXE = 'DELUXE',
  ICU = 'ICU',
  NICU = 'NICU',
  EMERGENCY = 'EMERGENCY',
  MATERNITY = 'MATERNITY',
  PEDIATRIC = 'PEDIATRIC',
  ISOLATION = 'ISOLATION',
  SURGICAL = 'SURGICAL',
}

export enum AdmissionStatus {
  PENDING = 'PENDING',
  ADMITTED = 'ADMITTED',
  TRANSFERRED = 'TRANSFERRED',
  DISCHARGED = 'DISCHARGED',
  DECEASED = 'DECEASED',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  PARTIAL = 'PARTIAL',
  PAID = 'PAID',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  CARD = 'CARD',
  BANK = 'BANK',
  ONLINE = 'ONLINE',
  WALLET = 'WALLET',
  INSURANCE = 'INSURANCE',
  CREDIT = 'CREDIT',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  PARTIAL = 'PARTIAL',
}

export enum LabOrderStatus {
  ORDERED = 'ORDERED',
  SAMPLE_COLLECTED = 'SAMPLE_COLLECTED',
  RECEIVED = 'RECEIVED',
  PROCESSING = 'PROCESSING',
  RESULT_READY = 'RESULT_READY',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  REPORTED = 'REPORTED',
  REJECTED = 'REJECTED',
}

export enum RadiologyOrderStatus {
  ORDERED = 'ORDERED',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  IMAGES_UPLOADED = 'IMAGES_UPLOADED',
  REPORTED = 'REPORTED',
  VERIFIED = 'VERIFIED',
  APPROVED = 'APPROVED',
  DELIVERED = 'DELIVERED',
}

export enum OTStatus {
  REQUESTED = 'REQUESTED',
  APPROVED = 'APPROVED',
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum InventoryTransactionType {
  RECEIPT = 'RECEIPT',
  ISSUE = 'ISSUE',
  TRANSFER_IN = 'TRANSFER_IN',
  TRANSFER_OUT = 'TRANSFER_OUT',
  ADJUSTMENT = 'ADJUSTMENT',
  CONSUMPTION = 'CONSUMPTION',
  RETURN = 'RETURN',
  OPENING = 'OPENING',
}

export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  CONFIRMED = 'CONFIRMED',
  PARTIAL_RECEIVED = 'PARTIAL_RECEIVED',
  RECEIVED = 'RECEIVED',
  INVOICED = 'INVOICED',
  CANCELLED = 'CANCELLED',
}

export enum LeaveStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
}

export enum EnquiryStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  QUALIFIED = 'QUALIFIED',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WHATSAPP = 'WHATSAPP',
  PUSH = 'PUSH',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  VIEW = 'VIEW',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  EXPORT = 'EXPORT',
  PRINT = 'PRINT',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum BloodGroup {
  A_POS = 'A+',
  A_NEG = 'A-',
  B_POS = 'B+',
  B_NEG = 'B-',
  AB_POS = 'AB+',
  AB_NEG = 'AB-',
  O_POS = 'O+',
  O_NEG = 'O-',
}

export enum MaritalStatus {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  DIVORCED = 'DIVORCED',
  WIDOWED = 'WIDOWED',
}